### ISSUE TITLE
Difference to forked project

### ISSUE THREAD

**Issue by BioPhoton** [dvelasquez/lighthouse-plugin-crux#23]
Hi @dvelasquez thx for your work front off!

Could you help me to understand the diff between this and the original code?

Thx!

**Comment by dvelasquez** [comment]
Hi @BioPhoton, thanks for the question.

The main difference is the data source. The original project uses the PageSpeedInsights API, which comes with 2 limitations: speed and concurrency (it takes between 15 to 45 seconds and you can only run 2 in parallel), this happens because PageSpeedInsights also analyses the page with lighthouse and make a request to the CrUX API internally.
On the other hand this project uses the CrUX API directly thus having the results in less than half a second and removing the concurrency problems.

Besides the data source, this project is built with typescript.

**Comment by BioPhoton** [comment]
Thx @dvelasquez for that information it is that of an important difference that I say this deserves a space in the main readme,👍 if u like.
